# fly.toml app configuration file generated for backend-core-withered-forest-7653 on 2026-01-23T21:02:51+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-core-withered-forest-7653'
primary_region = 'fra'

# This gives you 512MB of virtual RAM for FREE.
# It prevents OOM crashes on a 256MB machine.
swap_size_mb = 512

[build]

[http_service]
  internal_port = 8080
  force_https = true
  
  # 'stop' saves money by turning the app off when no one is using it.
  auto_stop_machines = 'stop'
  
  # 'true' ensures it wakes up instantly when your website calls it.
  auto_start_machines = true
  
  # '0' ensures you aren't paying for a machine while you sleep.
  min_machines_running = 0
  
  processes = ["app"]

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256